#!/bin/bash

set -x

USERNAME="$(logname)"

WHONIX_LOCAL_SIGNING_KEY_FOLDER="/home/$USERNAME/gpg-test"

mkdir --parents "$WHONIX_LOCAL_SIGNING_KEY_FOLDER"

## chmod 700, so gpg will not complain about folder permissions
chmod 700 "$WHONIX_LOCAL_SIGNING_KEY_FOLDER"

## http://www.gnupg.org/documentation/manuals/gnupg-devel/Unattended-GPG-key-generation.html

echo "
   Key-Type: RSA
   Key-Length: 4096
   Subkey-Type: RSA
   Subkey-Length: 4096
   Name-Real: Whonix auto generated local APT signing key
   Name-Email: whonix@local-signing.key
   Expire-Date: 0
   Preferences: SHA512 SHA384 SHA256 SHA224 AES256 AES192 AES CAST5 ZLIB BZIP2 ZIP Uncompressed
" | gpg \
--no-default-keyring \
--homedir "$WHONIX_LOCAL_SIGNING_KEY_FOLDER" \
--batch \
--gen-key
